[IMP] ocabot merge : check line in migration issue
OCA/oca-github-bot pull request #192
Opened 2022-07-01 15:19 UTC by legalsylvain

DO NOT REVIEW

2022-10-10 09:43 UTC, SirTakobi requested changes

2022-10-10 09:43 UTC, SirTakobi commented on src/oca_github_bot/tasks/migration_issue_bot.py
> +            lines.append(line[:3] + "x" + line[4:])
Thanks for the PR!
```suggestion
            checked_line = line.replace('[ ]', '[x]', 1)
            lines.append(checked_line)
```
I think the suggested change is safer if the line is not exactly what has been created by https://github.com/OCA/oca-github-bot/blob/c8555ba1cd604028d511b29cfa65010dcf7c8403/src/oca_github_bot/tasks/migration_issue_bot.py#L32

For instance, in https://github.com/OCA/l10n-italy/issues/1905 we have indented the lines to highlight dependencies.
Regex might be used better but I think this is already a good start :)

2023-01-27 15:28 UTC, legalsylvain commented
Hi.
@SirTakobi : I merged your Proposal. Thanks, and sorry for the delay.
@all : I deployed this PR on my bot and the feature works correctly. (Ref : https://github.com/grap/grap-odoo-custom/issues/279)

I think it could be merged safely.

2023-01-27 17:28 UTC, pedrobaeza approved these changes

2023-02-07 13:06 UTC, pedrobaeza commented
@sbidoul this one is very interesting to be merged and deployed for synchronizing the issue information with the reality.

2023-02-07 14:20 UTC, sbidoul reviewed
Ah, I had review comments that I forgot to submit, sorry about that.

2023-02-07 14:38 UTC, SirTakobi approved these changes
Thanks!
I don't know about the policy for the commits in the repository, but only one commit should be enough: you can squash what I suggested in your changes.

2023-02-07 20:09 UTC, legalsylvain reviewed
Hi @sbidoul. I applied the changes you proposed. Thanks for your review ! 

Regarding the refactor you propose, I don't have a clear point of view, and no time in the next week to work on the bot.
We can merge it as it, and make some refactor work in a next sprint, or let the PR unmerged if you think it's a blocking point.

> I don't know about the policy for the commits in the repository, but only one commit should be enough: you can squash what I suggested in your changes.

@SirTakobi : I don't know about policy, but in that case, the first commit is mine, and the second one is your. If I squash, we will lose that information.

2023-02-07 20:10 UTC, legalsylvain commented
/ocabot rebase

2023-02-07 20:22 UTC, legalsylvain commented
/ocabot rebase

2023-04-08 10:11 UTC, legalsylvain commented on src/oca_github_bot/tasks/merge_bot.py
> +            migration_issue.edit(body=new_body)
Done here : https://github.com/OCA/oca-github-bot/pull/192/commits/fd2107475cccbdc1e76efc7061e8326f1c63b10f

let me know if all is ok or if it requires some changes.

thanks !

2023-06-17 09:09 UTC, merged

2023-06-17 09:11 UTC, pedrobaeza commented
Bravo! Are you going to deploy this for doing some checks on real scenarios?

2023-06-17 10:51 UTC, sbidoul commented
@pedrobaeza it is now deployed.

2023-06-17 11:34 UTC, pedrobaeza commented
Thanks. I'll check and tell you back if anything wrong.

2023-06-18 17:35 UTC, pedrobaeza commented
It seems not working:

```
The merge process could not be finalized because an exception was raised: _find_issue() missing 1 required positional argument: 'target_branch'.
```

https://github.com/OCA/server-backend/pull/202

cc @legalsylvain @sbidoul